version: '3.5'

services:
  mariadb:
    image: wodby/mariadb
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
      - .docker-data/mariadb:/var/lib/mysql
  php:
    image: "wodby/drupal-php:${PHP_VERSION}"
    environment:
      #PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: ${PROJECT_NAME}
      DB_PASSWORD: ${MYSQL_PWD}
      DB_NAME: ${PROJECT_NAME}
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_TRIGGER: ses
    volumes:
      - .:/var/www/html

  nginx:
    image: wodby/nginx
    depends_on:
      - php
    environment:
      #NGINX_SERVER_EXTRA_CONF_FILEPATH: /var/www/html/nginx.conf/vhost.conf
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: drupal9
      NGINX_SERVER_ROOT: /var/www/html/web
    networks:
      default:
        aliases:
          - apache-${PROJECT_NAME}
      traefik:
    volumes:
      - .:/var/www/html
    # Options for macOS users (https://wodby.com/docs/stacks/wordpress/local#docker-for-mac)
    #      - ./:/var/www/html:cached # User-guided caching
    #      - docker-sync:/var/www/html # Docker-sync
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.docker.localhost"
      - "traefik.enable=true"
      - "traefik.port=80"

networks:
  default:
    name: ${PROJECT_NAME}-docker
    labels:
      - "launchpad.managed_project=${PROJECT_NAME}"
      - "launchpad.project_https="
      - "launchpad.project_roles=apache,pma,mailhog,solr,pmca"
      - "launchpad.project_sync_strategy=nfs"
      - "launchpad.project_xipio=true"
      - "launchpad.entrypoint=apache"
  traefik:
    external:
      name: traefik

volumes:
  ssh_agent:
    external: true
    name: ssh_agent
